jobs:
  build:
    name: Ci
    runs-on: ubuntu-20.04

    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Install Prerequisites
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Check
        run: ./action/main

name: Check

on:
  schedule:
    - cron: "20 */6 * * *"
